### ISSUE TITLE
Requests to management API fail without Authorization header

### ISSUE THREAD

**Issue by JBetz** [alasconnect/auth0#3]
All of the management API functions need to sent an API token through the Authorization header, which currently isn't possible, and causes requests to fail with 401 "Missing Authentication". Should be as simple as adding an additional parameter of type `AccessToken` that gets used to build the header.

**Comment by boj** [comment]
@JBetz Unfortunately we never ended up using this library (yet?), so aren't actively working on it at the moment. If you send in a PR with a working fix I'd be happy to merge it in.

**Comment by JBetz** [comment]
@boj Ah, too bad. Do you have any sort of notes on what's left to implement? I'm building a Haskell backend that needs to talk to Auth0, so I'll likely need at least a subset of this library to work. So yeah, I definitely want to help move it forward.

Out of curiosity, why'd you decide not to use this library?

**Comment by boj** [comment]
As far as I know I implemented all of the Auth0 interfaces, but only tested the few I cared about.

Why we are not using this kind of convoluted. We took over a project that was being written in C# and was using Auth0, so I implemented this library thinking that functionality was necessary. Turns out it was overkill for the project, and using something like Azure's various integrated AD solutions made more sense for us (we handle a lot of onsite customer networks and services, not internet facing apps).

**Comment by JBetz** [comment]
Yeah, it looks you got a good start. I don't think it will take much to make it useful for my needs.

My (professional) use case is fairly narrow, but it is for an internet facing app, so makes sense for our purposes. The one disappointing thing so far is that the admin dashboard isn't really something we're going to want to make our clients use, so the plan there is to create our own that focuses on what we actually want along and also on what we need beyond Auth0. So yeah, that will be the primary use case for this library, as a backend for that admin panel.

Work on it has been delayed the past couple weeks, but I'm planning to get back into it soon and we'll see how it goes. :)

**Comment by JBetz** [comment]
Got a PR coming to fix this. Will open it once #5 is resolved.

**Comment by boj** [comment]
Great, thanks for the PR!

**Comment by JBetz** [comment]
Resolved by #6.
